# alertmanager.yml

route:
  receiver: 'Mail Alert'
  # group_by: [ alertname ]
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
 - name: 'Mail Alert'
   email_configs:
      - smarthost: 'mail.sanlamamba.com:26'
        auth_username: 'test@sanlamamba.com'
        auth_password: "Gouverneur2024+"
        require_tls: true
        from: 'test@sanlamamba.com'
        to: 'help@sanlamamba.com'
        headers:
          subject: 'Prometheus Mail Alerts'
