- name: Set up monitoring tools
  block:
    - name: Vérification d'existance du repo
      stat:
        path: '/home/{{ monitor_host_username }}/monitor'
      register: monitor

    - name: Cloner le dépôt GitHub
      git:
        repo: 'https://github.com/MokhtarBeny/NSA_800.git'
        dest: '/home/{{ monitor_host_username }}/monitor'
        clone: yes
        update: yes
      become_user: '{{ monitor_host_username }}'
      when: not monitor.stat.exists

    - name: Construire et Lancer Docker Compose
      command:
        cmd: "{{ item.cmd }}"
        chdir: /home/{{ monitor_host_username }}/monitor
      become_user: '{{ monitor_host_username }}'
      loop:
        - { cmd: 'sudo docker compose build' }
        - { cmd: 'sudo docker compose up -d' }
