global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093
scrape_configs:
 - job_name: ulises-prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: traefik
   static_configs:
    - targets:
       - traefik:8082
 - job_name: node
   static_configs:
    - targets:
       - node-exporter:9100
 - job_name: app
   static_configs:
    - targets:
       - app:8081
 - job_name: db
   static_configs:
    - targets:
       - db:3306
   relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'mysqld_exporter:9104'
 - job_name: mysqld_exporter
   static_configs:
    - targets: ['mysqld_exporter:9104']