groups:
 - name: example
   rules:
   - alert: InstanceDown
     expr: up == 0
     for: 1m
     labels:
      severity: page
     annotations:
       summary: "Instance {{ $labels.instance }} down"
       description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
   
   - alert: SqlServerDown
     expr: mssql_up == 0
     for: 0m
     labels:
      severity: critical
     annotations:
       summary: SQL Server down (instance {{ $labels.instance }})
       description: "SQL server instance is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"