name: Security Scanning with Trivy

on:
  push:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: docker build -t sanlamamba/lostops_nsa_800:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner on image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'sanlamamba/lostops_nsa_800:${{ github.sha }}'
          format: 'table'

      - name: Run Trivy vulnerability scanner on root filesystem
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'scan.sarif'

      - name: Upload SARIF output to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'scan.sarif'
